# Préparation des Données

Cette première étape consiste à charger les données avec pandas et de le préparer à l'entraînement.

In [8]:
import pandas as pd
import glob
import os
from pandas_profiling import ProfileReport
current_directory = os.getcwd()
repertory_path = os.path.abspath(os.path.join(current_directory, "..", ".."))

Maintenant on peut importer les données

In [9]:
file_paths = glob.glob(repertory_path + "/.MGL_869_Laboratoire/ML_Pipeline/Data/*.csv")
data = pd.concat((pd.read_csv(file) for file in file_paths), ignore_index=True)
data.tail()

,Bug,FileName,AvgCyclomatic,AvgCountLine,AvgCountLineBlank,AvgCountLineCode,AvgCountLineComment,AvgCyclomaticModified,AvgCyclomaticStrict,AvgCyclomaticStrictModified,...,MaxInheritanceTree,MaxNesting,PercentLackOfCohesion,PercentLackOfCohesionModified,RatioCommentToCode,SumCyclomatic,SumCyclomaticModified,SumCyclomaticStrict,SumCyclomaticStrictModified,SumEssential
40860,0,testthrift_types.h,14.0,38.0,0.0,38.0,0.0,14.0,14.0,14.0,...,NaN,1.0,NaN,NaN,0.07,14.0,14.0,14.0,14.0,13.0
40861,0,thrift_grammar.java,10.0,44.0,0.0,43.0,1.0,8.0,10.0,8.0,...,NaN,4.0,NaN,NaN,0.03,675.0,537.0,677.0,539.0,244.0
40862,0,thrift_grammarConstants.java,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,0.0,NaN,NaN,0.81,0.0,0.0,0.0,0.0,0.0
40863,0,thrift_grammarTokenManager.java,14.0,42.0,0.0,41.0,0.0,8.0,14.0,8.0,...,NaN,6.0,NaN,NaN,0.01,502.0,272.0,512.0,282.0,380.0
40864,0,thrift_grammarTreeConstants.java,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,0.0,NaN,NaN,0.08,0.0,0.0,0.0,0.0,0.0

Nous avons donc un total de 40865 entrées pour commencer. Voici le type de chacune de nos variables et des informations sur notre

In [10]:
data.dtypes
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40865 entries, 0 to 40864
Data columns (total 75 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Bug                                 40865 non-null  int64
 1   FileName                            40865 non-null  object
 2   AvgCyclomatic                       40865 non-null  float64
 3   AvgCountLine                        40865 non-null  float64
 4   AvgCountLineBlank                   40865 non-null  float64
 5   AvgCountLineCode                    40865 non-null  float64
 6   AvgCountLineComment                 40865 non-null  float64
 7   AvgCyclomaticModified               40865 non-null  float64
 8   AvgCyclomaticStrict                 40865 non-null  float64
 9   AvgCyclomaticStrictModified         40865 non-null  float64
 10  AvgEssential                        40865 non-null  float64
 11  CCViolDensityCode                   40865 non-null  float64
 12  CCViolDensityLine                   40865 non-null  float64
 13  CountCCViol                         40865 non-null  float64
 14  CountCCViolType                     40865 non-null  float64
 15  CountClassBase                      0 non-null      float64
 16  CountClassCoupled                   0 non-null      float64
 17  CountClassCoupledModified           0 non-null      float64
 18  CountClassDerived                   0 non-null      float64
 19  CountDeclClass                      40865 non-null  float64
 20  CountDeclClassMethod                40592 non-null  float64
 21  CountDeclClassVariable              40592 non-null  float64
 22  CountDeclExecutableUnit             40592 non-null  float64
 23  CountDeclFile                       0 non-null      float64
 24  CountDeclFileCode                   0 non-null      float64
 25  CountDeclFileHeader                 0 non-null      float64
 26  CountDeclFunction                   40865 non-null  float64
 27  CountDeclInstanceMethod             40592 non-null  float64
 28  CountDeclInstanceVariable           40592 non-null  float64
 29  CountDeclInstanceVariablePrivate    0 non-null      float64
 30  CountDeclInstanceVariableProtected  0 non-null      float64
 31  CountDeclInstanceVariablePublic     0 non-null      float64
 32  CountDeclMethod                     40592 non-null  float64
 33  CountDeclMethodAll                  0 non-null      float64
 34  CountDeclMethodConst                0 non-null      float64
 35  CountDeclMethodDefault              40592 non-null  float64
 36  CountDeclMethodFriend               0 non-null      float64
 37  CountDeclMethodPrivate              40592 non-null  float64
 38  CountDeclMethodProtected            40592 non-null  float64
 39  CountDeclMethodPublic               40592 non-null  float64
 40  CountInput                          0 non-null      float64
 41  CountLine                           40865 non-null  float64
 42  CountLineBlank                      40865 non-null  float64
 43  CountLineCode                       40865 non-null  float64
 44  CountLineCodeDecl                   40865 non-null  float64
 45  CountLineCodeExe                    40865 non-null  float64
 46  CountLineComment                    40865 non-null  float64
 47  CountLineInactive                   273 non-null    float64
 48  CountLinePreprocessor               273 non-null    float64
 49  CountOutput                         0 non-null      float64
 50  CountSemicolon                      40865 non-null  float64
 51  CountStmt                           40865 non-null  float64
 52  CountStmtDecl                       40865 non-null  float64
 53  CountStmtEmpty                      273 non-null    float64
 54  CountStmtExe                        40865 non-null  float64
 55  Cyclomatic                          0 non-null      float64
 56  CyclomaticModified                  0 non-null      float64
 57  CyclomaticStrict                    0 non-null      float64
 58  CyclomaticStrictModified            0 non-null      float64
 59  Essential                           0 non-null      float64
 60  MaxCyclomatic                       40865 non-null  float64
 61  MaxCyclomaticModified               40865 non-null  float64
 62  MaxCyclomaticStrict                 40865 non-null  float64
 63  MaxCyclomaticStrictModified         40865 non-null  float64
 64  MaxEssential                        40865 non-null  float64
 65  MaxInheritanceTree                  0 non-null      float64
 66  MaxNesting                          40865 non-null  float64
 67  PercentLackOfCohesion               0 non-null      float64
 68  PercentLackOfCohesionModified       0 non-null      float64
 69  RatioCommentToCode                  40865 non-null  float64
 70  SumCyclomatic                       40865 non-null  float64
 71  SumCyclomaticModified               40865 non-null  float64
 72  SumCyclomaticStrict                 40865 non-null  float64
 73  SumCyclomaticStrictModified         40865 non-null  float64
 74  SumEssential                        40865 non-null  float64
dtypes: float64(73), int64(1), object(1)
memory usage: 23.4+ MB

Un premier ménage s'impose - Commençons nous débarraser des noms des fichiers et des colonnes qui ne nous intéressent pas:

In [11]:
columns_to_keep = [
    "Bug","AvgCyclomatic", "AvgCyclomaticModified", "AvgCyclomaticStrict", "AvgEssential", "AvgCountLine", "AvgCountLineBlank",
    "AvgCountLineCode", "AvgCountLineComment", "CountDeclClass", "CountDeclClassMethod", "CountDeclClassVariable", 
    "CountDeclFunction", "CountDeclInstanceMethod", "CountDeclInstanceVariable", "CountDeclMethod", 
    "CountDeclMethodDefault", "CountDeclMethodPrivate", "CountDeclMethodProtected", "CountDeclMethodPublic", 
    "CountLine", "CountLineBlank", "CountLineCode", "CountLineCodeDecl", "CountLineCodeExe", "CountLineComment", 
    "CountSemicolon", "CountStmt", "CountStmtDecl", "CountStmtExe", "MaxCyclomatic", "MaxCyclomaticModified", 
    "MaxCyclomaticStrict", "RatioCommentToCode", "SumCyclomatic", "SumCyclomaticModified", "SumCyclomaticStrict", 
    "SumEssential", "MaxNesting"]

data = data[columns_to_keep]
data.head()

,Bug,AvgCyclomatic,AvgCyclomaticModified,AvgCyclomaticStrict,AvgEssential,AvgCountLine,AvgCountLineBlank,AvgCountLineCode,AvgCountLineComment,CountDeclClass,...,CountStmtExe,MaxCyclomatic,MaxCyclomaticModified,MaxCyclomaticStrict,RatioCommentToCode,SumCyclomatic,SumCyclomaticModified,SumCyclomaticStrict,SumEssential,MaxNesting
0,0,2.0,2.0,2.0,1.0,11.0,0.0,11.0,0.0,9.0,...,143.0,8.0,8.0,8.0,0.11,58.0,58.0,61.0,34.0,4.0
1,1,4.0,2.0,4.0,1.0,14.0,0.0,13.0,1.0,1.0,...,112.0,42.0,9.0,42.0,0.10,66.0,30.0,66.0,22.0,2.0
2,0,4.0,4.0,4.0,1.0,18.0,1.0,15.0,2.0,7.0,...,303.0,15.0,15.0,16.0,0.14,124.0,124.0,133.0,40.0,5.0
3,0,1.0,1.0,1.0,1.0,2.0,0.0,2.0,0.0,1.0,...,5.0,1.0,1.0,1.0,0.95,5.0,5.0,5.0,5.0,0.0
4,1,2.0,2.0,3.0,1.0,10.0,1.0,8.0,1.0,1.0,...,129.0,11.0,11.0,15.0,0.24,58.0,58.0,71.0,32.0,4.0

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40865 entries, 0 to 40864
Data columns (total 39 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Bug                        40865 non-null  int64
 1   AvgCyclomatic              40865 non-null  float64
 2   AvgCyclomaticModified      40865 non-null  float64
 3   AvgCyclomaticStrict        40865 non-null  float64
 4   AvgEssential               40865 non-null  float64
 5   AvgCountLine               40865 non-null  float64
 6   AvgCountLineBlank          40865 non-null  float64
 7   AvgCountLineCode           40865 non-null  float64
 8   AvgCountLineComment        40865 non-null  float64
 9   CountDeclClass             40865 non-null  float64
 10  CountDeclClassMethod       40592 non-null  float64
 11  CountDeclClassVariable     40592 non-null  float64
 12  CountDeclFunction          40865 non-null  float64
 13  CountDeclInstanceMethod    40592 non-null  float64
 14  CountDeclInstanceVariable  40592 non-null  float64
 15  CountDeclMethod            40592 non-null  float64
 16  CountDeclMethodDefault     40592 non-null  float64
 17  CountDeclMethodPrivate     40592 non-null  float64
 18  CountDeclMethodProtected   40592 non-null  float64
 19  CountDeclMethodPublic      40592 non-null  float64
 20  CountLine                  40865 non-null  float64
 21  CountLineBlank             40865 non-null  float64
 22  CountLineCode              40865 non-null  float64
 23  CountLineCodeDecl          40865 non-null  float64
 24  CountLineCodeExe           40865 non-null  float64
 25  CountLineComment           40865 non-null  float64
 26  CountSemicolon             40865 non-null  float64
 27  CountStmt                  40865 non-null  float64
 28  CountStmtDecl              40865 non-null  float64
 29  CountStmtExe               40865 non-null  float64
 30  MaxCyclomatic              40865 non-null  float64
 31  MaxCyclomaticModified      40865 non-null  float64
 32  MaxCyclomaticStrict        40865 non-null  float64
 33  RatioCommentToCode         40865 non-null  float64
 34  SumCyclomatic              40865 non-null  float64
 35  SumCyclomaticModified      40865 non-null  float64
 36  SumCyclomaticStrict        40865 non-null  float64
 37  SumEssential               40865 non-null  float64
 38  MaxNesting                 40865 non-null  float64
dtypes: float64(38), int64(1)
memory usage: 12.2 MB

On peut produire un rapport sur nos données au format HTML

In [ ]:
from pandas_profiling import ProfileReport

profile = ProfileReport(data, 
                        title='Apache Hive Bug Dataset Profile Report',
                        pool_size=4,
                        html={'style': {'full_width': True}})
profile.to_notebook_iframe()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

On se retrouve avec 38 variables, toutes définies pour chacune de nos entrées. Les données sont prêtes à être partionnées pour ensuite être entraînées. On peut sauvegarder ces données au format CSV.

In [ ]:
data.to_csv("Data_Preparation_Output.csv",index=False)